
// This file has been generated by the GUI designer. Do not modify.

internal partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action AnimusIRCAction;
	
	private global::Gtk.Action ServerAction;
	
	private global::Gtk.VBox vbox_container_main;
	
	private global::Gtk.MenuBar menu_main;
	
	private global::Gtk.HBox hbox_main;
	
	private global::Gtk.ScrolledWindow scrolled_channels;
	
	private global::Gtk.TreeView treeview_servers;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Label lbl_topic;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TextView txt_chat;
	
	private global::Gtk.Entry entry_chat;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView treeview_users;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.AnimusIRCAction = new global::Gtk.Action ("AnimusIRCAction", global::Mono.Unix.Catalog.GetString ("Animus IRC"), null, null);
		this.AnimusIRCAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Animus IRC");
		w1.Add (this.AnimusIRCAction, null);
		this.ServerAction = new global::Gtk.Action ("ServerAction", global::Mono.Unix.Catalog.GetString ("Server"), null, null);
		this.ServerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Server");
		w1.Add (this.ServerAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox_container_main = new global::Gtk.VBox ();
		this.vbox_container_main.Name = "vbox_container_main";
		this.vbox_container_main.Spacing = 6;
		// Container child vbox_container_main.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menu_main\'><menu name=\'AnimusIRCAction\' action=\'AnimusIRCActio" +
		"n\'/><menu name=\'ServerAction\' action=\'ServerAction\'/></menubar></ui>");
		this.menu_main = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menu_main")));
		this.menu_main.Name = "menu_main";
		this.vbox_container_main.Add (this.menu_main);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox_container_main [this.menu_main]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox_container_main.Gtk.Box+BoxChild
		this.hbox_main = new global::Gtk.HBox ();
		this.hbox_main.Name = "hbox_main";
		this.hbox_main.Spacing = 6;
		// Container child hbox_main.Gtk.Box+BoxChild
		this.scrolled_channels = new global::Gtk.ScrolledWindow ();
		this.scrolled_channels.WidthRequest = 150;
		this.scrolled_channels.Name = "scrolled_channels";
		this.scrolled_channels.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolled_channels.Gtk.Container+ContainerChild
		this.treeview_servers = new global::Gtk.TreeView ();
		this.treeview_servers.CanFocus = true;
		this.treeview_servers.Name = "treeview_servers";
		this.scrolled_channels.Add (this.treeview_servers);
		this.hbox_main.Add (this.scrolled_channels);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox_main [this.scrolled_channels]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox_main.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.lbl_topic = new global::Gtk.Label ();
		this.lbl_topic.Name = "lbl_topic";
		this.lbl_topic.LabelProp = global::Mono.Unix.Catalog.GetString ("{{ topic }}");
		this.vbox2.Add (this.lbl_topic);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lbl_topic]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox2.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.txt_chat = new global::Gtk.TextView ();
		this.txt_chat.CanFocus = true;
		this.txt_chat.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
		this.txt_chat.Name = "txt_chat";
		this.txt_chat.Editable = false;
		this.txt_chat.Overwrite = true;
		this.GtkScrolledWindow1.Add (this.txt_chat);
		this.vbox2.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow1]));
		w8.Position = 2;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entry_chat = new global::Gtk.Entry ();
		this.entry_chat.CanFocus = true;
		this.entry_chat.Name = "entry_chat";
		this.entry_chat.IsEditable = true;
		this.entry_chat.InvisibleChar = '●';
		this.vbox2.Add (this.entry_chat);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entry_chat]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox_main.Add (this.vbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox_main [this.vbox2]));
		w10.Position = 1;
		// Container child hbox_main.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.WidthRequest = 150;
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview_users = new global::Gtk.TreeView ();
		this.treeview_users.CanFocus = true;
		this.treeview_users.Name = "treeview_users";
		this.GtkScrolledWindow.Add (this.treeview_users);
		this.hbox_main.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox_main [this.GtkScrolledWindow]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox_container_main.Add (this.hbox_main);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox_container_main [this.hbox_main]));
		w13.Position = 1;
		this.Add (this.vbox_container_main);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 799;
		this.DefaultHeight = 510;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.entry_chat.Activated += new global::System.EventHandler (this.OnEntryChatActivated);
	}
}
